### ISSUE TITLE
bin folder

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/plant-stress-ontology#2]
I think you should delete the folder named 'bin' from the repo

**Comment by austinmeier** [comment]
Why?

**Comment by marieALaporte** [comment]
The bin directory should be used only by the ontology editors. Not by the ontology users. This is why I think it should be deleted. But this is ok to keep it for now, for test purposes.

**Comment by austinmeier** [comment]
okay, yeah.  I agree.  I don't want the users to be running robot or pattern apply.  But it's just nice to have in the repo for now because I can always point to that /bin no matter what computer I'm using (including the OSU cluster)

it will be removed when we migrate this test ontology to the Planteome project.
