### ISSUE TITLE
Cannot import test_aps_diseases.owl AND upper_level.owl at the same time??

### ISSUE THREAD

**Issue by austinmeier** [Planteome/plant-stress-ontology#7]
@marieALaporte why can I not have oops-edit.owl import both of these ontologies at the same time?  I manually added the import to the ontology imports section in Protege, but when I save and reload, it always defaults back to only importing test_aps_diseases.owl, and leaves upper_level.owl out.  Do I need to modify something to allow multiple direct imports?

**Comment by marieALaporte** [comment]
I think that your problem is caused by the fact that the 2 ontologies test_aps_diseases.owl and upper_level.owl are sharing the same namespace (http://purl.obolibrary.org/obo/auto). They are defined as being the same ontology: the URI of the 2 ontologies is the same. Some interesting reading about that: https://www.w3.org/TR/2004/REC-owl-guide-20040210/#StructureOfOntologies

How to fix that:
test_aps_diseases.owl : The URI of this ontology should be something like http://purl.obolibrary.org/obo/oops/patternapply/test_aps_diseases.owl
upper_level.owl : The URI of this ontology should be something like http://purl.obolibrary.org/obo/oops/patternapply/upper_level.owl

Then you will have I think to remove the old import (http://purl.obolibrary.org/obo/auto) and import the 2 files (in Protégé) and that should work.

**Comment by austinmeier** [comment]
Ohhhh, I was wondering why the namespace for those ontologies was "auto".  Is that a byproduct of using the same python script to generate them?  (apply-pattern.py)
Thanks for the lesson, and quick reply.  I'll do some tinkering today.

**Comment by marieALaporte** [comment]
I think you can customize the ontology URI by playing with the lines 26/27 of the apply-pattern.py script

**Comment by austinmeier** [comment]
Yeah, I assumed there was a line or two in there that caused them both to be the same.  Luckily, it's in python, and I can actually read python!

edit: yup, it's a simple command line argument that allows you to just change the name at the time of running!  That Chris, he thinks of everything.
